import { browser, expect, $ } from "@wdio/globals";
import { describe, it, before } from "mocha";
import { obsidianPage } from "wdio-obsidian-service";
import { promises as fs } from "node:fs";
import { fileURLToPath } from "node:url";
import { openPluginSettings, switchTab } from "../settings-helpers";

// QA 1.1: the full settings-tab inventory — field ORDER + default VALUE +
// "Requires container restart" label across all four tabs. Instead of a manual
// eyeball audit, serialize the REAL rendered settings DOM (the only layer that
// reflects true order + rendered dropdown labels) to a structured snapshot and
// diff it against a committed reference. Any added/removed/reordered field, a
// changed default, a flipped restart label, or a renamed dropdown option fails
// the test until the reference is deliberately re-blessed:
//
//   OAS_UPDATE_SETTINGS_SNAPSHOT=1 npm run test:e2e:headless
//   npx prettier --write test/e2e/fixtures/settings-inventory.json   # match repo style
//
// captures the reference, then review it against this scenario and commit it.

const TABS = ["General", "Terminal", "MCP", "Advanced"] as const;
const FIXTURE = fileURLToPath(new URL("../fixtures/settings-inventory.json", import.meta.url));
const UPDATE = process.env.OAS_UPDATE_SETTINGS_SNAPSHOT === "1";
// The MCP auth token auto-generates a random value on first load; redact it so
// the snapshot stays deterministic (its presence + Regenerate button are kept).
const TOKEN_FIELD = "Auth token";
// SecretComponent renders a non-standard control; pin it by name so it doesn't
// misclassify, and never capture a secret value.
const SECRET_FIELD = "Sudo password";

interface SettingRecord {
	type: "heading" | "toggle" | "dropdown" | "input" | "list" | "secret" | "other";
	name: string;
	value?: string;
	entries?: string[];
	disabled?: boolean;
	buttons?: string[];
	requiresRestart?: boolean;
}

/** Serialize the active tab's settings rows in DOM order. Runs in-page. */
function extractActiveTab(): Promise<SettingRecord[]> {
	return browser.executeObsidian(
		(_ctx, { tokenField, secretField }: { tokenField: string; secretField: string }) => {
			const content = document.querySelector(".sandbox-settings-content");
			if (!content) return [];
			const txt = (el: Element | null) => (el?.textContent ?? "").trim();

			return Array.from(content.querySelectorAll(".setting-item")).map((item) => {
				const name = txt(item.querySelector(".setting-item-name"));
				if (item.classList.contains("setting-item-heading")) {
					return { type: "heading", name };
				}

				const requiresRestart = (
					item.querySelector(".setting-item-description")?.textContent ?? ""
				).includes("Requires container restart.");
				const buttons = Array.from(item.querySelectorAll("button"))
					.map((b) => txt(b))
					.filter(Boolean);
				const withMeta = (rec: SettingRecord, withButtons = false): SettingRecord => {
					if (withButtons && buttons.length) rec.buttons = buttons;
					if (requiresRestart) rec.requiresRestart = true;
					return rec;
				};

				if (name === secretField)
					return withMeta({ type: "secret", name, value: "<secret>" });

				const control = item.querySelector(".setting-item-control");
				const checkbox = control?.querySelector<HTMLInputElement>('input[type="checkbox"]');
				const select = control?.querySelector<HTMLSelectElement>("select");
				const input = control?.querySelector<HTMLInputElement>(
					"input:not([type='checkbox'])",
				);
				const isList =
					item.classList.contains("sandbox-settings-list-editor") ||
					!!item.querySelector(".sandbox-settings-list-add");

				if (checkbox)
					return withMeta({
						type: "toggle",
						name,
						value: checkbox.checked ? "on" : "off",
					});
				if (select) {
					const opt = select.options[select.selectedIndex];
					return withMeta({ type: "dropdown", name, value: txt(opt) });
				}
				if (isList) {
					const entries = Array.from(
						item.querySelectorAll(".sandbox-settings-list-entry-text"),
					).map((e) => txt(e));
					return withMeta({ type: "list", name, entries });
				}
				if (input) {
					const rec: SettingRecord = {
						type: "input",
						name,
						value: name === tokenField ? "<auto-generated>" : input.value,
					};
					if (input.disabled) rec.disabled = true;
					return withMeta(rec, true);
				}
				return withMeta({ type: "other", name }, true);
			}) as SettingRecord[];
		},
		{ tokenField: TOKEN_FIELD, secretField: SECRET_FIELD },
	);
}

describe("Settings inventory snapshot (1.1)", function () {
	before(async function () {
		await obsidianPage.resetVault();
		await openPluginSettings();
	});

	it("matches the committed reference for every tab (order + defaults + restart labels)", async function () {
		const actual: Record<string, SettingRecord[]> = {};
		for (const tab of TABS) {
			await switchTab(tab);
			await $(".sandbox-settings-content .setting-item").waitForExist({
				timeout: 5000,
				timeoutMsg: `no settings rendered for the ${tab} tab`,
			});
			actual[tab] = await extractActiveTab();
		}

		if (UPDATE) {
			await fs.writeFile(FIXTURE, JSON.stringify(actual, null, 2) + "\n");
			console.log(`[settings-inventory] wrote reference (${TABS.length} tabs) to ${FIXTURE}`);
			return;
		}

		const raw = await fs.readFile(FIXTURE, "utf8").catch(() => {
			throw new Error(
				"No committed settings-inventory.json. Run with OAS_UPDATE_SETTINGS_SNAPSHOT=1 to capture it, review against qa-test-plan.md 1.1, and commit.",
			);
		});
		expect(actual).toEqual(JSON.parse(raw) as Record<string, SettingRecord[]>);
	});
});
